# Generated by Django 5.1.5 on 2025-01-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitasdespesas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receitasdespesas',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
