# Generated by Django 5.1.5 on 2025-01-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitasdespesas', '0002_rename_descrição_receitasdespesas_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitasdespesas',
            name='usuario_id',
            field=models.EmailField(max_length=254),
        ),
    ]
