# Generated by Django 5.1.5 on 2025-01-22 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitasdespesas', '0003_alter_receitasdespesas_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receitasdespesas',
            old_name='usuario_id',
            new_name='usuario_email',
        ),
    ]
