# Generated by Django 5.1.5 on 2025-01-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailUsuario', models.CharField(max_length=300)),
                ('bancoUsuario', models.CharField(max_length=255)),
                ('agenciaUsuario', models.IntegerField()),
                ('contaUsuario', models.IntegerField()),
            ],
        ),
    ]
